- name: Testing the azure_rm_virtualmachine
  hosts: localhost
  connection: local
  tasks:

  - name: azure init
    azure_rm_virtualmachine:
       resource_group: mperz
       name: testvm10
       vm_size: Standard_D1
       admin_username: centos
       ssh_password: false
       image:
         offer: CentOS
         publisher: OpenLogic
         sku: '7.1'
         version: latest
