---
- name: testing blocks
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
    - block:
       - name: copying in a block
         copy: src=/tmp/test1.txt dest=/tmp/loops
      rescue:
       - include: copyblock.yml
      #always:
       #- debug: msg="This message will always display."

    #- block:
     #  - block:
     #     - block:
      #       - debug: msg="nesting some blocks" 
