---

- name: Testing canceled zombie jobs
  hosts: Bugtest
  remote_user: ubuntu
  become: yes
  
  tasks:
  
  - name: install some stuff
    apt: name={{item}} state=absent
    with_items:
    - git
    
    
  - name: create new user
    user: name={{item}} state=absent
    with_items:
    - ansible
    - gmuniz
