
- src: https://git.ingroovesplatform.net/infrastructure/ansible/roles/PostgreSQL
  scm: git
  version: 1.7.1
  name: postgresql

- src: https://git.ingroovesplatform.net/infrastructure/ansible/roles/Wal-E
  scm: git
  version: 1.0.0
  name: wal-e

- src: https://git.ingroovesplatform.net/infrastructure/ansible/roles/Logrotate
  scm: git
  version: 0.0.4
  name: logrotate
